apiVersion: v1
kind: Secret
metadata:
  name: shop-secrets
  namespace: shop-micro
type: Opaque
stringData:
  JWT_SECRET: "replace-me"
  USER_DB_URI: "mongodb+srv://<user>:<pass>@<cluster>/UserDB?retryWrites=true&w=majority"
  PRODUCT_DB_URI: "mongodb+srv://<user>:<pass>@<cluster>/products?retryWrites=true&w=majority"
  CART_DB_URI: "mongodb+srv://<user>:<pass>@<cluster>/CartDB?retryWrites=true&w=majority"
  ORDER_DB_URI: "mongodb+srv://<user>:<pass>@<cluster>/OrderDB?retryWrites=true&w=majority"
  PAYMENT_DB_URI: "mongodb+srv://<user>:<pass>@<cluster>/PaymentDB?retryWrites=true&w=majority"
  REVIEW_DB_URI: "mongodb+srv://<user>:<pass>@<cluster>/ReviewDB?retryWrites=true&w=majority"
